Repository Linkup-3mw/frontend, pull requests merged in 2024-06, with the labels that each got.

#42 [Feat] Signup API Connection
  package.json
  pnpm-lock.yaml
  src/app/(auth)/components/Test.tsx
  src/app/(auth)/components/signup/CompanyInput.tsx
  src/app/(auth)/components/signup/EmailInput.tsx
  src/app/(auth)/components/signup/NicknameInput.tsx
  src/app/(auth)/components/signup/SignupForm.tsx
  src/app/layout.tsx
  src/app/service/auth.ts
  src/app/service/category.ts
  src/context/QueryProvider.tsx
  src/hooks/useCategory.ts
  src/styles/globals.css
Labels: API

#43 [Feat] Signin API Connection
  package.json
  pnpm-lock.yaml
  src/app/(auth)/components/signin/Login.tsx
  src/app/(auth)/components/signin/LoginCheckbox.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/auth/authOptions.ts
  src/app/page.tsx
  src/app/serverAction/auth.ts
  src/app/service/auth.ts
  src/context/AuthorizationHeader.tsx
  src/types/next-auth.d.ts
  src/types/user.ts
  src/utils/axios.ts
Labels: API

#49 [Feat] Fix Signin
  src/app/(board)/components/.gitkeep
  src/app/(board)/constants/.gitkeep
  src/app/(board)/detail/page.tsx
  src/app/(board)/list/page.tsx
  src/app/api/auth/authOptions.ts
  src/app/common/header/HamburgerMenuModal.tsx
  src/app/common/header/Header.tsx
  src/app/layout.tsx
  src/app/serverAction/auth.ts
  src/app/service/auth.ts
  src/context/AuthorizationHeader.tsx
  src/types/next-auth.d.ts
  src/utils/axios.ts
  vercel.json
Labels: enhancement

#54 [Design] Add Form mobile responsive
  src/app/(auth)/(pages)/signin/page.tsx
  src/app/(auth)/(pages)/signup/page.tsx
  src/app/(auth)/(pages)/terms/page.tsx
  src/app/(auth)/components/common/ButtonInInput.tsx
  src/app/(auth)/components/common/Container.tsx
  src/app/(auth)/components/common/RoundedFrame.tsx
  src/app/(auth)/components/common/TogglePassword.tsx
  src/app/(auth)/components/signin/Login.tsx
  src/app/(auth)/components/signin/LoginCheckbox.tsx
  src/app/(auth)/components/signup/EmailInput.tsx
  src/app/(auth)/components/signup/SignupForm.tsx
  src/app/(auth)/components/terms/ArrowBtn.tsx
  src/app/(auth)/components/terms/TermToggleBox.tsx
  src/app/(auth)/components/terms/Terms.tsx
  src/app/(auth)/components/terms/TermsContent.tsx
  src/app/api/auth/authOptions.ts
  src/app/common/components/form/BlueSquareBtn.tsx
  src/app/common/components/form/CheckBox.tsx
  src/app/common/components/form/Input.tsx
  src/app/common/components/form/InputBox.tsx
  src/app/common/components/form/MobileBackBtn.tsx
  src/app/common/components/form/RadioButton.tsx
  src/app/common/components/form/RoundedCheckbox.tsx
  src/app/common/components/icons/Check.tsx
  src/app/common/components/icons/Eyes.tsx
Labels: design

#53 [Design] buildingList publishing
  .eslintrc.json
  db.json
  public/svg/reservation/service/릴랙스룸.svg
  public/svg/reservation/service/맥주.svg
  public/svg/reservation/service/우편함.svg
  public/svg/reservation/service/폰부스.svg
  src/app/(search)/atom/search.ts
  src/app/(search)/map/components/BuildingFilter.tsx
  src/app/(search)/map/components/BuildingImageSlider.tsx
  src/app/(search)/map/components/BuildingInfo.tsx
  src/app/(search)/map/components/BuildingInfoServiceView.tsx
  src/app/(search)/map/components/BuildingItem.tsx
  src/app/(search)/map/components/BuildingList.tsx
  src/app/(search)/map/components/Chart.tsx
  src/app/(search)/map/components/ClubInfo.tsx
  src/app/(search)/map/components/LocationButton.tsx
  src/app/(search)/map/components/Map.tsx
  src/app/(search)/map/components/Marker.tsx
  src/app/(search)/map/components/ReviewInfo.tsx
  src/app/(search)/map/components/Zoom.tsx
  src/app/(search)/map/page.tsx
  src/app/(search)/reservation/[id]/components/MonthPassMembership.tsx
  src/app/(search)/reservation/[id]/components/OnePassMembership.tsx
  src/app/(search)/reservation/[id]/components/table/mobile/OpenDeskMobile.tsx
  src/app/(search)/reservation/[id]/page.tsx
  src/app/page.tsx
  src/styles/reservation.css
Labels: design

#60 [Design] ClubPage and ClubCard mobile publishing
  src/app/common/header/HamburgerMenuModal.tsx
  src/app/common/header/Header.tsx
  src/app/common/header/HeaderMenu.tsx
  src/app/common/header/Profile.tsx
  src/app/community/(pages)/club/page.tsx
  src/app/community/components/club/CategoryDropdown.tsx
  src/app/community/components/club/Club.tsx
  src/app/community/components/club/ClubCard.tsx
  src/app/community/components/club/ClubList.tsx
  src/app/community/components/club/MyClubMenu.tsx
  src/app/community/components/club/PlaceDropdown.tsx
  src/app/community/components/club/SearchInput.tsx
  src/app/community/layout.tsx
  src/styles/globals.css
Labels: design

#56 [Fix] Main home page
  .eslintrc.json
  src/app/(home)/components/noneLogin/FlipSwiper.tsx
  src/app/page.tsx
Labels: fix

#63 [Fix] Signin token refresh
  src/app/api/auth/authOptions.ts
Labels: bug

#64 [Design] Club Detail Publishing
  src/app/(auth)/components/terms/ArrowBtn.tsx
  src/app/common/components/form/Calendar.tsx
  src/app/common/components/form/EnterButton.tsx
  src/app/common/components/icons/BlackArrow.tsx
  src/app/common/components/icons/CrownBadge.tsx
  src/app/common/components/icons/HeartIcon.tsx
  src/app/common/components/icons/MeetingIcons.tsx
  src/app/common/components/icons/MessengerIcon.tsx
  src/app/common/components/icons/PeopleIcons.tsx
  src/app/common/components/icons/SquareBlueArrow.tsx
  src/app/common/components/icons/XIcon.tsx
  src/app/common/components/user/Avatar.tsx
  src/app/community/(pages)/club/[id]/page.tsx
  src/app/community/components/club/MemberModal.tsx
  src/app/community/components/club/clubDetail/BlueSquareBtn.tsx
  src/app/community/components/club/clubDetail/BoardCard.tsx
  src/app/community/components/club/clubDetail/BoardDetail.tsx
  src/app/community/components/club/clubDetail/BoardDetailTopBtn.tsx
  src/app/community/components/club/clubDetail/BoardsSection.tsx
  src/app/community/components/club/clubDetail/HeartBtn.tsx
  src/app/community/components/club/clubDetail/IntroduceSection.tsx
  src/app/community/components/club/clubDetail/IntroduceTopBtn.tsx
  src/app/community/components/club/clubDetail/MeetingCard.tsx
  src/app/community/components/club/clubDetail/MeetingRegister.tsx
  src/app/community/components/club/clubDetail/MemberSwiper.tsx
  src/app/community/components/club/clubDetail/MoreBtn.tsx
  src/app/community/components/club/clubDetail/NoneMemberBoardsSection.tsx
  src/app/community/components/club/clubDetail/NoneMemberIntroduceSection.tsx
  src/app/community/components/club/clubDetail/RegisterBoard.tsx
  src/app/community/components/club/clubDetail/SelectDateInput.tsx
  src/app/community/components/club/clubDetail/TabMenu.tsx
  src/app/community/components/club/clubDetail/TabMenuWrap.tsx
  src/app/community/components/club/clubDetail/TopBackbtn.tsx
  src/app/community/components/club/clubDetail/WriteBtn.tsx
  src/app/community/constants/clubDetail.ts
  src/styles/globals.css
  src/utils/params.ts
Labels: design

#67 [Design] Fix Header mobile publishing
  src/app/common/header/HamburgerMenuModal.tsx
  src/app/common/header/Header.tsx
  src/app/common/header/HeaderMenu.tsx
  src/app/common/header/MobileHeader.tsx
  src/app/common/header/Profile.tsx
  src/styles/globals.css
Labels: design

#69 [Fix] Terms Screen flickering phenomenon
  src/app/(auth)/(pages)/terms/page.tsx
  src/app/(auth)/components/terms/Terms.tsx
  src/app/api/auth/authOptions.ts
Labels: bug

#70 [Design] Add Club mobile publishing and Fix Header
  src/app/common/header/HamburgerMenuModal.tsx
  src/app/common/header/Header.tsx
  src/app/community/components/club/CategoryDropdown.tsx
  src/app/community/components/club/Club.tsx
  src/app/community/components/club/ClubCard.tsx
  src/app/community/components/club/ClubList.tsx
  src/app/community/components/club/MenuButtons.tsx
  src/app/community/components/club/MyClubsSubMenu.tsx
  src/app/community/components/club/PlaceDropdown.tsx
  src/app/community/components/club/SearchInput.tsx
  src/app/community/components/club/TeamExclusionButton.tsx
Labels: design, fix

#71 [Feat] Add filtering function, only cities can be filtered
  public/images/icons/tail.png
  public/svg/map/tail.svg
  public/svg/map/tailblue.svg
  src/app/(search)/atom/search.ts
  src/app/(search)/map/components/BuildingFilter.tsx
  src/app/(search)/map/components/BuildingImageSlider.tsx
  src/app/(search)/map/components/BuildingInfo.tsx
  src/app/(search)/map/components/BuildingInfoServiceView.tsx
  src/app/(search)/map/components/BuildingItem.tsx
  src/app/(search)/map/components/BuildingList.tsx
  src/app/(search)/map/components/Map.tsx
  src/app/(search)/map/components/Marker.tsx
  src/app/(search)/map/page.tsx
  src/app/(search)/reservation/[id]/components/EnterPriseMembership.tsx
  src/app/(search)/reservation/[id]/components/MonthPassMembership.tsx
  src/app/(search)/reservation/[id]/components/OnePassMembership.tsx
  src/app/(search)/reservation/[id]/components/ReservationInfo.tsx
  src/app/(search)/reservation/[id]/components/table/OpenTable.tsx
  src/app/(search)/reservation/[id]/page.tsx
  src/app/(search)/reservation/myMembership/components/AllSearchMembership.tsx
  src/app/(search)/reservation/myMembership/components/EnterPriseMembershipSearch.tsx
  src/app/(search)/reservation/myMembership/page.tsx
  src/styles/reservation.css
  src/types/office/office.ts
Labels: API

#73 [Fix] Change token delivery method
  src/app/api/auth/authOptions.ts
  src/app/serverAction/auth.ts
  src/context/AuthorizationHeader.tsx
  src/utils/axios.ts
Labels: bug, API

#78 [Design] Club mobile publishing
  src/app/common/header/MobileHeader.tsx
  src/app/community/(pages)/club/manage/[id]/page.tsx
  src/app/community/(pages)/club/request/page.tsx
  src/app/community/components/CommunityNav.tsx
  src/app/community/components/club/ClubCard.tsx
  src/app/community/components/club/ClubRequestForm.tsx
  src/app/community/components/club/CreateGroupForm.tsx
  src/app/community/components/club/Modal.tsx
  src/app/community/components/club/common/ButtonInInput.tsx
  src/app/community/components/club/common/Modal.tsx
  src/app/community/components/club/common/RoundedFrame.tsx
  src/app/community/data/applications.js
  src/app/community/data/members.js
  src/app/community/layout.tsx
Labels: design

#81 [Fix] terms route
  src/app/(auth)/components/terms/Terms.tsx
Labels: bug

#87 [Fix] Axios interceptors
  src/utils/axios.ts
  src/utils/getSession.ts
Labels: bug

#89 [Fix] Fix Club and Header
  src/api/club/searchClubs.ts
  src/app/common/header/HamburgerMenuModal.tsx
  src/app/common/header/Header.tsx
  src/app/common/header/MobileHeader.tsx
  src/app/common/header/Profile.tsx
  src/app/community/(pages)/club/create/page.tsx
  src/app/community/(pages)/club/request/page.tsx
  src/app/community/components/club/Club.tsx
  src/app/community/components/club/CreateGroupForm.tsx
  src/app/community/components/club/MenuButtons.tsx
  src/app/community/components/club/PaginatedClubs.tsx
  src/app/community/components/club/PlaceDropdown.tsx
  src/app/community/components/club/RenderClubs.tsx
  src/app/community/components/club/clubMenu/AllMenu/AllMenu.tsx
  src/app/community/components/club/clubMenu/BookmarkMenu/BookmarkMenu.tsx
  src/app/community/components/club/clubMenu/MyClubsMenu/MyClubsMenu.tsx
  src/app/community/components/club/common/AddClubButton.tsx
  src/app/community/layout.tsx
  src/app/layout.tsx
  src/utils/session.ts
Labels: enhancement, fix

#90 [Fix] Signin and Signup
  package.json
  src/app/(auth)/components/common/ButtonInInput.tsx
  src/app/(auth)/components/signin/Login.tsx
  src/app/(auth)/components/signup/CompanyInput.tsx
  src/app/(auth)/components/signup/EmailInput.tsx
  src/app/(auth)/components/signup/NicknameInput.tsx
  src/app/(auth)/components/signup/SignupForm.tsx
  src/app/serverAction/auth.ts
  src/hooks/useCategory.ts
Labels: bug, enhancement

#92 [Fix] Header SSR and Login Refresh
  src/app/(auth)/components/signin/Login.tsx
  src/app/common/header/Header.tsx
  src/app/layout.tsx
Labels: bug

#98 [Feat] Club Detail Page
  src/app/(auth)/components/signup/NicknameInput.tsx
  src/app/(auth)/components/terms/ArrowBtn.tsx
  src/app/common/components/form/Calendar.tsx
  src/app/common/components/form/EnterButton.tsx
  src/app/common/components/frame/CircleLoader.tsx
  src/app/common/components/icons/XIcon.tsx
  src/app/common/components/modal/Alert.tsx
  src/app/common/components/modal/EncourageLoginAlert.tsx
  src/app/common/components/modal/RouterPushAlert.tsx
  src/app/common/components/modal/confirm.tsx
  src/app/common/components/user/Avatar.tsx
  src/app/community/(pages)/club/[id]/[type]/detail/page.tsx
  src/app/community/(pages)/club/[id]/[type]/page.tsx
  src/app/community/(pages)/club/[id]/[type]/register/page.tsx
  src/app/community/(pages)/club/[id]/layout.tsx
  src/app/community/(pages)/club/[id]/page.tsx
  src/app/community/atoms/clubDetail.ts
  src/app/community/components/club/clubDetail/BoardCard.tsx
  src/app/community/components/club/clubDetail/BoardDetail.tsx
  src/app/community/components/club/clubDetail/BoardDetailTopBtn.tsx
  src/app/community/components/club/clubDetail/BoardList.tsx
  src/app/community/components/club/clubDetail/BoardRegister.tsx
  src/app/community/components/club/clubDetail/BoardsSection.tsx
  src/app/community/components/club/clubDetail/CommentInput.tsx
  src/app/community/components/club/clubDetail/DetailContent.tsx
  src/app/community/components/club/clubDetail/HeartBtn.tsx
  src/app/community/components/club/clubDetail/IntroduceSection.tsx
  src/app/community/components/club/clubDetail/IntroduceTopBtn.tsx
  src/app/community/components/club/clubDetail/MeetingCard.tsx
  src/app/community/components/club/clubDetail/MeetingList.tsx
  src/app/community/components/club/clubDetail/MeetingRegister.tsx
  src/app/community/components/club/clubDetail/MemberSwiper.tsx
  src/app/community/components/club/clubDetail/NoDataMessage.tsx
  src/app/community/components/club/clubDetail/NoneMemberBoardsSection.tsx
  src/app/community/components/club/clubDetail/NoneMemberIntroduceSection.tsx
  src/app/community/components/club/clubDetail/RegisterBoard.tsx
  src/app/community/components/club/clubDetail/SectionBoard.tsx
  src/app/community/components/club/clubDetail/SectionIntrduce.tsx
  src/app/community/components/club/clubDetail/SelectDateInput.tsx
  src/app/community/components/club/clubDetail/TabMenu.tsx
  src/app/community/components/club/clubDetail/TabMenuWrap.tsx
  src/app/community/constants/clubDetail.ts
  src/app/service/clubDetail.ts
  src/context/QueryProvider.tsx
  src/hooks/useClubDetail.ts
  src/types/club/detail/clubDetail.ts
  src/types/user.ts
  src/utils/utils.ts
Labels: enhancement, API

#118 [Fix] Club Detail Page
  src/app/community/(pages)/club/[id]/layout.tsx
  src/app/community/components/ApplyModal.tsx
  src/app/community/components/club/clubDetail/BlueSquareBtn.tsx
  src/app/community/components/club/clubDetail/BoardDetail.tsx
  src/app/community/components/club/clubDetail/BoardList.tsx
  src/app/community/components/club/clubDetail/BoardRegister.tsx
  src/app/community/components/club/clubDetail/IntroduceDetail.tsx
  src/app/community/components/club/clubDetail/IntroduceSection.tsx
  src/app/community/components/club/clubDetail/IntroduceTopBtn.tsx
  src/app/community/components/club/clubDetail/MeetingList.tsx
  src/app/community/components/club/clubDetail/MeetingRegister.tsx
  src/app/community/components/club/clubDetail/MemberSwiper.tsx
  src/app/community/components/club/clubDetail/NoneMemberIntroduceSection.tsx
  src/app/community/components/club/clubDetail/SectionIntrduce.tsx
  src/app/community/components/club/clubDetail/TabMenuWrap.tsx
  src/app/community/components/club/clubDetail/TopBackbtn.tsx
  src/app/layout.tsx
  src/app/service/clubDetail.ts
  src/styles/globals.css
Labels: enhancement
