Repository Linkup-3mw/frontend, pull requests merged in 2024-05, with the labels that each got.

#9 [Chore] Community file structure changes and add CommunityNav
  public/svg/communityNav/coffeechatIcon.svg
  public/svg/communityNav/coffeechatIconActive.svg
  public/svg/communityNav/collabIcon.svg
  public/svg/communityNav/collabIconActive.svg
  public/svg/communityNav/cowIcon.svg
  public/svg/communityNav/cowIconActive.svg
  public/svg/communityNav/eventIcon.svg
  public/svg/communityNav/eventIconActive.svg
  public/svg/communityNav/homeIcon.svg
  public/svg/communityNav/homeIconActive.svg
  src/app/common/header/Header.tsx
  src/app/common/header/HeaderNav.tsx
  src/app/common/header/index.ts
  src/app/community/(pages)/club/page.tsx
  src/app/community/(pages)/coffeechat/page.tsx
  src/app/community/(pages)/collaboration/PartnerContent.tsx
  src/app/community/(pages)/collaboration/ProjectContent.tsx
  src/app/community/(pages)/collaboration/page.tsx
  src/app/community/(pages)/event/page.tsx
  src/app/community/components/CommunityNav.tsx
  src/app/community/components/club/.gitkeep
  src/app/community/components/coffeechat/.gitkeep
  src/app/community/components/collaboration/.gitkeep
  src/app/community/components/event/.gitkeep
  src/app/community/layout.tsx
  src/app/community/page.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/styles/globals.css
  tsconfig.json
Labels: design, setting, fix

#11 [Design] SignIn & Signup Markup
  package.json
  pnpm-lock.yaml
  src/app/(auth)/(pages)/signin/page.tsx
  src/app/(auth)/(pages)/signup/page.tsx
  src/app/(auth)/(pages)/terms/page.tsx
  src/app/(auth)/components/common/ButtonInInput.tsx
  src/app/(auth)/components/common/Container.tsx
  src/app/(auth)/components/common/RoundedFrame.tsx
  src/app/(auth)/components/common/TogglePassword.tsx
  src/app/(auth)/components/signin/Login.tsx
  src/app/(auth)/components/signin/LoginCheckbox.tsx
  src/app/(auth)/components/signup/BirthdayInput.tsx
  src/app/(auth)/components/signup/CompanyInput.tsx
  src/app/(auth)/components/signup/EmailInput.tsx
  src/app/(auth)/components/signup/PasswordInput.tsx
  src/app/(auth)/components/signup/SignupForm.tsx
  src/app/(auth)/components/terms/ArrowBtn.tsx
  src/app/(auth)/components/terms/TermToggleBox.tsx
  src/app/(auth)/components/terms/Terms.tsx
  src/app/(auth)/components/terms/TermsContent.tsx
  src/app/(auth)/constants/validation.ts
  src/app/api/auth/[...nextauth]/route.ts
  src/app/common/components/form/BlueSquareBtn.tsx
  src/app/common/components/form/CheckBox.tsx
  src/app/common/components/form/Input.tsx
  src/app/common/components/form/InputBox.tsx
  src/app/common/components/form/RadioButton.tsx
  src/app/common/components/form/RoundedCheckbox.tsx
  src/app/common/components/icons/Check.tsx
  src/app/common/components/icons/CircleWithCheck.tsx
  src/app/common/components/icons/Eyes.tsx
  src/app/common/components/icons/XIcon.tsx
  src/app/layout.tsx
  src/context/AuthContext.tsx
  src/context/AuthorizationHeader.tsx
  src/middleware.ts
  src/styles/globals.css
  src/types/next-auth.d.ts
  src/utils/axios.ts
  src/utils/cookie.ts
  tailwind.config.ts
Labels: design, setting

#17 [Design] add Map BuildingList & kakao Marker add location, zoom in and out button
  db.json
  package.json
  pnpm-lock.yaml
  public/db.json
  public/images/office/check.png
  public/svg/map/Arrow.svg
  public/svg/map/cow.svg
  public/svg/map/geolocation.svg
  public/svg/map/star.svg
  public/svg/map/zoomIn.svg
  public/svg/map/zoomOut.svg
  src/app/(search)/atom/search.ts
  src/app/(search)/map/components/BuildingFilter.tsx
  src/app/(search)/map/components/BuildingItem.tsx
  src/app/(search)/map/components/BuildingList.tsx
  src/app/(search)/map/components/Loader/FullPageLoader.tsx
  src/app/(search)/map/components/LocationButton.tsx
  src/app/(search)/map/components/Map.tsx
  src/app/(search)/map/components/Marker.tsx
  src/app/(search)/map/components/Zoom.tsx
  src/app/(search)/map/page.tsx
  src/app/api/office/route.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/context/Provider.tsx
  src/types/office/office.ts
  tailwind.config.ts
Labels: design

#19 [Feat] Signup page mock api connection
  db.json
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/app/(auth)/components/signup/BirthdayInput.tsx
  src/app/(auth)/components/signup/CompanyInput.tsx
  src/app/(auth)/components/signup/EmailInput.tsx
  src/app/(auth)/components/signup/NicknameInput.tsx
  src/app/(auth)/components/signup/PasswordInput.tsx
  src/app/(auth)/components/signup/PhoneNumberInput.tsx
  src/app/(auth)/components/signup/SignupForm.tsx
  src/app/(auth)/constants/validation.ts
  src/app/common/components/form/Input.tsx
  src/app/service/auth.ts
  src/utils/axios.ts
Labels: enhancement, API

#21 [Feat] Signin page mock api connection
  src/app/(auth)/components/signin/Login.tsx
  src/app/(auth)/components/signin/LoginCheckbox.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/service/auth.ts
  src/types/next-auth.d.ts
  src/types/user.ts
Labels: enhancement, API

#23 [Design] None-login homepage publishing
  package.json
  pnpm-lock.yaml
  public/images/home/bg_home.jpg
  public/images/home/img_card_1.png
  public/images/home/img_card_2.png
  public/images/home/img_card_3.png
  public/images/home/img_circle_office.png
  public/images/home/img_circle_office2.png
  public/images/home/img_circle_office3.png
  public/images/home/img_circle_office4.png
  public/images/home/img_circle_office5.png
  public/images/home/img_office_1.png
  public/images/home/img_office_2.png
  public/images/home/img_office_3.png
  public/images/home/img_office_4.png
  src/app/(auth)/components/Test.tsx
  src/app/(home)/components/noneLogin/FlipCard.tsx
  src/app/(home)/components/noneLogin/FlipSwiper.tsx
  src/app/(home)/components/noneLogin/NoneLoginHome.tsx
  src/app/(home)/components/noneLogin/OfficeCard.tsx
  src/app/(home)/components/noneLogin/RatePlanCard.tsx
  src/app/(home)/constants/home.ts
  src/app/common/components/frame/ContentWrap.tsx
  src/app/page.tsx
  src/assets/fonts/SB_Aggro_M.otf
  src/styles/globals.css
  src/styles/typography.ts
  tailwind.config.ts
Labels: design

#24 [Design] club publishing and add form validation
  package.json
  pnpm-lock.yaml
  public/images/club/example.jpg
  public/svg/club/arrowDown.svg
  public/svg/club/arrowUp.svg
  public/svg/club/bookmarkedHeart.svg
  public/svg/club/crownIcon.svg
  public/svg/club/locationIcon.svg
  public/svg/club/peoplesIcon.svg
  public/svg/club/remove.svg
  public/svg/club/reset.svg
  public/svg/club/search.svg
  public/svg/club/unbookmarkedHeart.svg
  src/app/common/header/Header.tsx
  src/app/community/(pages)/club/page.tsx
  src/app/community/components/club/.gitkeep
  src/app/community/components/club/CategoryDropdown.tsx
  src/app/community/components/club/ClubCard.tsx
  src/app/community/components/club/CreateGroupForm copy.tsx
  src/app/community/components/club/CreateGroupForm.tsx
  src/app/community/components/club/ManageClub.tsx
  src/app/community/components/club/MenuButtons.tsx
  src/app/community/components/club/Modal.tsx
  src/app/community/components/club/MyClubMenu.tsx
  src/app/community/components/club/Pagination.tsx
  src/app/community/components/club/PlaceDropdown.tsx
  src/app/community/components/club/SearchInput.tsx
  src/app/community/components/club/SearchOffice.tsx
  src/app/community/components/club/TeamExclusionButton.tsx
  src/app/community/data/clubs.js
  src/styles/globals.css
  tailwind.config.ts
  tsconfig.json
Labels: design, enhancement

#28 [Chore] solved globals.css problem
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/app/common/header/Header.tsx
  src/styles/globals.css
Labels: fix
